name: Daily WhatsApp Tech Digest

on:
  schedule:
    - cron: "0 18 * * *"  # 13:00 America/Lima = 18:00 UTC (aprox; revisa horario de verano)
  workflow_dispatch:

jobs:
  run-digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Run digest
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          WHATSAPP_FROM: ${{ secrets.WHATSAPP_FROM }}
          WHATSAPP_TO: ${{ secrets.WHATSAPP_TO }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TZ: America/Lima
        run: python main.py
